# This is a workflow for publish package via lerna to npm
name: lerna-publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
    - run: |
        npm i
#        echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        npm run lerna:publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
