# This is a workflow for publish package via lerna to npm
name: lerna-publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm i
        echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        npm run lerna:publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
